### ISSUE TITLE
Lab 8 , Exercise 2 APIM Policy Issue

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#451]
# Module: 08
#### Step: 24

Description of issue

Please provide the following information:

While working with content validation policy at Exercise 2 - Step 24.
Review the results of the API request.

You should receive an error HTTP/1.1 502 Response Not Allowed.

Instead the response comes as 200 OK, I verified that the configuration of the policy is correct but we are not obtaining the expected result.

Please see the following screenshot for details:

![Lab8Error](https://user-images.githubusercontent.com/6410720/160001911-2c7a8640-b036-4749-ba57-136824b0b83f.png)

Am I missing something here?

Repro steps:

22.Back on the Design tab, in the list of operations, select Generate Payload, and then select the Test tab.
23. In the Generate Payload section, in the Template parameters subsection, in the VALUE text box of the n parameter, enter 512, and then select Send.

24. Review the results of the API request.

**Comment by donaldcng** [comment]
Same. Even I set the value from 128 to 1. It still returns 200 OK.

**Comment by WigF1** [comment]
Also have this issue, you can enter any value for 'n' that exceeds the policy and you still get a HTTP200.

**Comment by unaihuete93** [comment]
We also had this issue today

**Comment by dave-007** [comment]
Also had this issue. Found a relevant stackoverflow post.
https://stackoverflow.com/questions/70268178/apim-validate-content-on-consumption-tier
There is a workaround described there: https://stackoverflow.com/a/70624625/2934158.
Will investigate.

**Comment by WigF1** [comment]
The workaround is not applicable to our lab scenario and doesn't actually resolve anything when you change the errors-varibale-name to 'requestBodyValidation'. 

The calls still return a HTTP200 for sizes greater than that specified in the policy. See below example, policy set to 32 and 56 requested successfully. 

![image](https://user-images.githubusercontent.com/12164329/162129943-261ca97d-8b34-4d09-be9a-017a7c9564d8.png)

![image](https://user-images.githubusercontent.com/12164329/162130029-ba3a2ea3-aac9-4216-845c-aa1fdc8d099c.png)

**Comment by WigF1** [comment]
I believe the issue is because /bytes/{n} is returning an application/octet-stream and the policy only [now?] validates the below types:

![image](https://user-images.githubusercontent.com/12164329/162132342-7b8596cb-799a-4384-a1e9-577d65613a03.png)

**Comment by minaspap** [comment]
The policy does not even appear on the trace window. It seems like it is ignored.

**Comment by wi5nia** [comment]
Also confirming the issue, the policy even if hit in the debugger doesn't create proper validation errors.

**Comment by JeffKoMS** [comment]
Can others check two things to see if you're seeing the same thing? 

1. I've checked the Overview/Monitor and am not seeing any requests registering from any of the operations.
2. I've tried running the tools in the Diagnose and solve problems blade and each one errors out.

I'm going to try this in a non-consumption plan tomorrow.

**Comment by JeffKoMS** [comment]
> I believe the issue is because /bytes/{n} is returning an application/octet-stream and the policy only [now?] validates the below types:
> 
> ![image](https://user-images.githubusercontent.com/12164329/162132342-7b8596cb-799a-4384-a1e9-577d65613a03.png)

This is definitely the issue. The fix will require some major rewrites for that exercise so we're generating a JSON payload, adding schemas, etc. I may have a fix for this in the next week.

**Comment by JeffKoMS** [comment]
@WigF1 @cdanvergara @unaihuete93 @msftnutta 

Can you please review PR #469 ? This should fix the issue with the policies not returning the correct status codes. Though, I'm a bit worried the fix may introduce a bit too much complexity.

**Comment by cdanvergara** [comment]
Yes, works with the proposed changes.
Definitely some adjustments at Exercise 1, Task 3, Step 5 may be required as the method GET /bytes/{n} is no longer used and this step may create confusion. Probably the best it's to replace it with GET/json

**Comment by msftnutta** [comment]
@JeffKoMS  I just tested and I still get HTTP 200 Ok from the pull request that you mentioned. Did i miss something?

**Comment by JeffKoMS** [comment]
@msftnutta The steps worked for me two days ago, but not today. (Even setting the max payload size to 1 byte.) Not sure why you'd have to change the Backend processing of  echo-headers for generate-payload to work. They're different operations on different endpoints. The Backend settings of generate-payload didn't inherit anything from echo-headers.

**Comment by msftnutta** [comment]
@JeffKoMS I tested it today, the GET echo-headers is working for me but not for /bytes/{n}

Exercise 2 > Task 3 > Step 17

Wondering, whether we could remove this GET /bytes/{n} 

I think this lab is too complex

**Comment by unaihuete93** [comment]
I would day better delete the not working task (rather than leave it as it is), include later if we make it work.

**Comment by JeffKoMS** [comment]
I think we can do that. I'll remove it on Friday (they like us to do updates on Fridays).

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirmed this issue.
